# Part 2: Python + SQLite

In [1]:
import sqlite3
from sqlite3 import Error

## Example:

In [2]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

## Questions:

### Q10: Produce a list of facilities with a total revenue less than 1000. The output of facility name and total revenue, sorted by revenue.

In [3]:
'''
query10 = """
    SELECT name, revenue
    FROM 
      (SELECT f.name, 
      SUM(CASE WHEN b.memid = 0 THEN b.slots * f.guestcost
      ELSE b.slots * f.membercost END) AS revenue
      FROM Bookings as b
      INNER JOIN Facilities as f
      USING (facid)
      GROUP BY f.name) AS output WHERE revenue < 1000
    ORDER BY revenue;
    """
'''

def create_connection(db_file):
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    cur = conn.cursor()
    
    query10 = """
        SELECT name, revenue
        FROM 
          (SELECT f.name, 
          SUM(CASE WHEN b.memid = 0 THEN b.slots * f.guestcost
          ELSE b.slots * f.membercost END) AS revenue
          FROM Bookings as b
          INNER JOIN Facilities as f
          USING (facid)
          GROUP BY f.name) AS output WHERE revenue < 1000
        ORDER BY revenue;
        """
    cur.execute(query10)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

### Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order.

In [4]:
'''
query11 = """
    SELECT CONCAT(a.surname, ', ', a.firstname) AS member,
    CONCAT(b.surname, ', ', b.firstname) AS recommended_by
    FROM Members AS a
    LEFT JOIN Members AS b
    ON a.recommendedby = b.memid
    ORDER BY member
    """
'''

def create_connection(db_file):
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    cur = conn.cursor()
    
    query11 = """
        SELECT (a.surname || ', ' || a.firstname) AS member,
        (b.surname || ', ' || b.firstname) AS recommended_by
        FROM Members AS a
        LEFT JOIN Members AS b
        ON a.recommendedby = b.memid
        ORDER BY member
        """
    cur.execute(query11)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Bader, Florence', 'Stibbons, Ponder')
('Baker, Anne', 'Stibbons, Ponder')
('Baker, Timothy', 'Farrell, Jemima')
('Boothe, Tim', 'Rownam, Tim')
('Butters, Gerald', 'Smith, Darren')
('Coplin, Joan', 'Baker, Timothy')
('Crumpet, Erica', 'Smith, Tracy')
('Dare, Nancy', 'Joplette, Janice')
('Farrell, David', None)
('Farrell, Jemima', None)
('GUEST, GUEST', None)
('Genting, Matthew', 'Butters, Gerald')
('Hunt, John', 'Purview, Millicent')
('Jones, David', 'Joplette, Janice')
('Jones, Douglas', 'Jones, David')
('Joplette, Janice', 'Smith, Darren')
('Mackenzie, Anna', 'Smith, Darren')
('Owen, Charles', 'Smith, Darren')
('Pinker, David', 'Farrell, Jemima')
('Purview, Millicent', 'Smith, Tracy')
('Rownam, Tim', None)
('Rumney, Henrietta', 'Genting, Matthew')
('Sarwin, Ramnaresh', 'Bader, Florence')
('Smith, Darren', None)
('Smith, Darren', None)
('Smith, Jack', 'Smith, Darren')
('Smith, Tracy', None)
('Stibbons, Ponder', 'Tracy, Burton')
('Tracy, Burton', None)
('Tupperware, Hyacinth', None)
('Worthington-Smyth, Henry', 'Smith, Tracy')

### Q12: Find the facilities with their usage by member, but not guests.

In [5]:
'''
query12 = """
    SELECT f.name as facility_name, COUNT(memid) AS member_usage
    FROM 
      (SELECT b.facid, b.memid
      FROM Bookings as b
      WHERE b.memid !=0) AS output
    LEFT JOIN Facilities AS f 
    USING (facid)
    GROUP BY f.facid
    ORDER BY member_usage DESC;
    """
'''

def create_connection(db_file):
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    cur = conn.cursor()
    
    query12 = """
        SELECT f.name as facility_name, COUNT(memid) AS member_usage
        FROM 
          (SELECT b.facid, b.memid
          FROM Bookings as b
          WHERE b.memid !=0) AS output
        LEFT JOIN Facilities AS f 
        USING (facid)
        GROUP BY f.facid
        ORDER BY member_usage DESC;
        """
    cur.execute(query12)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Pool Table', 783)
('Snooker Table', 421)
('Massage Room 1', 421)
('Table Tennis', 385)
('Badminton Court', 344)
('Tennis Court 1', 308)
('Tennis Court 2', 276)
('Squash Court', 195)
('Massage Room 2', 27)

### Q13: Find the facilities usage by month, but not guests.

In [6]:
'''
query13 = """
    SELECT MONTH(b.starttime) AS month, f.name AS facility_name, COUNT(b.memid) AS member_usage
    FROM Bookings AS b
    INNER JOIN Facilities AS f
    USING (facid)
    WHERE b.memid != 0
    GROUP BY month, facility_name;
    """
'''

def create_connection(db_file):
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    cur = conn.cursor()
    
    query13 = """
        SELECT STRFTIME('%m', b.starttime) AS month, f.name AS facility_name, COUNT(b.memid) AS member_usage
        FROM Bookings AS b
        INNER JOIN Facilities AS f
        USING (facid)
        WHERE b.memid != 0
        GROUP BY month, facility_name;
        """
    cur.execute(query13)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('07', 'Badminton Court', 51)
('07', 'Massage Room 1', 77)
('07', 'Massage Room 2', 4)
('07', 'Pool Table', 103)
('07', 'Snooker Table', 68)
('07', 'Squash Court', 23)
('07', 'Table Tennis', 48)
('07', 'Tennis Court 1', 65)
('07', 'Tennis Court 2', 41)
('08', 'Badminton Court', 132)
('08', 'Massage Room 1', 153)
('08', 'Massage Room 2', 9)
('08', 'Pool Table', 272)
('08', 'Snooker Table', 154)
('08', 'Squash Court', 85)
('08', 'Table Tennis', 143)
('08', 'Tennis Court 1', 111)
('08', 'Tennis Court 2', 109)
('09', 'Badminton Court', 161)
('09', 'Massage Room 1', 191)
('09', 'Massage Room 2', 14)
('09', 'Pool Table', 408)
('09', 'Snooker Table', 199)
('09', 'Squash Court', 87)
('09', 'Table Tennis', 194)
('09', 'Tennis Court 1', 132)
('09', 'Tennis Court 2', 126)